apiVersion: apps/v1
kind: Deployment
metadata:
   name: nodejs-deployment
spec:
   replicas: 1
   selector:
     matchLabels:
       app: nodejs-app
   template:
     metadata:
       labels:
         app: nodejs-app
     spec:
      containers:
      - name: nodejs
        image: docker.io/ayushsingh1509/nodejs-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
               name: nodejs-config
               key: port
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
